Finix.UI/Areas/ATM/Controllers/AgriculturalInfoController.cs
using Finix.ATM.DTO;
using Finix.ATM.Facade;
using Finix.ATM.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Finix.UI.Areas.ATM.Controllers
{
    
    public class AgriculturalInfoController : Controller
    {
        private readonly LandUseFacade _facade = new LandUseFacade();
        private readonly LocationFacade _facadelocation = new LocationFacade();
        // GET: ATM/AgriculturalInfo
        public ActionResult Index()
        {
            return View();
        }
        public ActionResult getMonths()
        {
            var data = _facade.GetMonths();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getCropSeasons()
        {
            var data = _facade.GetCropSeasons();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #region Crop Calendar
        public ActionResult CropCalendar()
        {
            return View();
        }
        public ActionResult SaveCropCalendar(CropCalendarDto dto)
        {
            var result = _facade.SaveCropCalendar(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getCrops()
        {
            var data = _facade.GetCrops();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getCropCalendar(long? locid)
        {
            var data = _facade.GetCropCalendar(locid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getCropCalendarById(long id)
        {
            var data = _facade.GetCropCalendarById(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        } 
        #endregion

        #region Use of Waterbodies
        public ActionResult LandUse()
        {
            return View();
        }

        public ActionResult getLandTypes()
        {
            var data = _facade.GetLandTypes(true);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SaveLandUse(LandUseDto dto)
        {
            var result = _facade.SaveLandInfo(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getLandInfoById(long id)
        {
            var data = _facade.GetLandInfoById(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getLandList()
        {
            var data = _facade.GetLandList();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Hazard Calendar
        public ActionResult HazardCalendar()
        {
            return View();
        }
        public ActionResult SaveHazardCalendar(HazardLocationMappingDto dto)
        {
            var result = _facade.SaveHazardCalendar(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult getHazardCalendar(long? locid)
        {
            var data = _facade.GetHazardCalendar(locid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult getCalendarInfoByHazardId(long hazardid)
        {
            var data = _facade.GetCalendarByHazardId(hazardid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Agricultural Land Information
        public ActionResult AgriculturalLandInformation()
        {
            return View();
        }

        public ActionResult SaveAgriculturalLandInfo(AgriculturalLandInfoDto dto)
        {
            var result = _facade.SaveAgriculrulLandInfo(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AllAgriculturalLands(string sortOrder, long? up, long? locationid, int page = 1, int pageSize = 20)
        {
            ViewBag.CurrentSort = sortOrder;
            if (locationid != null)
                ViewBag.LocationId = (long)locationid;
            if (up != null)
                ViewBag.UP = (long)up;
            ViewBag.UPs = _facadelocation.GetLocationsByLevel(LocationLevel.UP, null);
            ViewBag.Wards = _facadelocation.GetLocationsByLevel(LocationLevel.Ward, up);

            var data = _facade.AgriculturalLandList(pageSize, page, locationid);
            return View(data);
        }

        public ActionResult getAgriculturalLandInfoById(long id)
        {
            var data = _facade.getAgriculturalLandInfoById(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        } 
        #endregion
    }
}

Finix.UI/Areas/ATM/Views/AgriculturalInfo/AgriculturalLandInformation.cshtml
@{
    ViewBag.Title = "Agricultural Land Information";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/AgriculturalInfo/AgriculturalLandInfo.js"></script>

@*<h2>Agricultural Land Info</h2>*@

<div class="panel-body rm" id="divLandUse">
    <br />
    <div class="container-fluid">
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Crop Season<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-6">
                <select type="text" class="form-control" data-bind="options:CropSeasons, value:CropSeasonId, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'SeasonName'"></select>
            </div>

        </div>
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">UP Name<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-6" data-bind="validationElement: ParentLocationId">
                <select type="text" class="form-control" data-bind="options:ParentLocations, value:ParentLocationId, optionsCaption:'Select UP', optionsValue:'Id', optionsText: 'LocationName'"></select>
            </div>

        </div>
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Location<span class="required">*</span> :</label>
            </div>

            <div class="col-sm-6" data-bind="validationElement: LocationId">
                <select type="text" class="form-control" data-bind="options:Locations, value:LocationId, optionsCaption:'Select Exact Location', optionsValue:'Id', optionsText: 'LocationName'"></select>
            </div>


        </div>
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Crop Name<span class="required">*</span> :</label>
            </div>

            <div class="col-sm-6">
                <select type="text" class="form-control" data-bind="options:Crops, value:CropId, optionsCaption:'Select Crop', optionsValue:'Id', optionsText: 'CropName'"></select>
            </div>

        </div>
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Production Per Decimal<span class="required">*</span> :</label>
            </div>

            <div class="col-sm-6">
                <input type="text" class="form-control" data-bind="value:Production,valueUpdate: 'keyup'" placeholder="Type Amount(Kg) Per Decimal" value="" />
            </div>

        </div>
        <br />
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Is Affected Before<span class="required">*</span> :</label>
            </div>

            <div class="col-sm-6">
                
                    <div class="row">
                        <div class="col-sm-12">
                            <div class="col-sm-4">
                                <label class="radio-inline"><input type="radio" name="optradio" data-bind="checked: AffectedBefore, value:true" /> Yes</label>
                            </div>
                            <div class="col-sm-4">
                                <label class="radio-inline"><input type="radio" name="optradio" data-bind="checked: AffectedBefore, value:false"  /> No</label>
                            </div>
                        </div>
                    </div>
               
            </div>
        </div>
        <br />
        <div class="form-group row row_design" data-bind="visible:AffectedBefore">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Affected Year :</label>
            </div>

            <div class="col-sm-6" >
                <input type="text" class="form-control" data-bind="value:AffectedYear,valueUpdate: 'keyup'" placeholder="Type a year" value="" />
            </div>

        </div>
        <div class="form-group row row_design" data-bind="visible:AffectedBefore">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Affected By Hazard :</label>
            </div>

            <div class="col-sm-6">
                <select type="text" class="form-control" data-bind="options:Hazards, value:HazardId, optionsCaption:'Select Hazard', optionsValue:'Id', optionsText: 'Name'"></select>
            </div>

        </div>
        <div class="form-group row row_design" data-bind="visible:AffectedBefore">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Damage(%) :</label>
            </div>

            <div class="col-sm-6">
                <input type="text" class="form-control" data-bind="value:DamagePercentage,valueUpdate: 'keyup'" placeholder="Damage in Parcentage" value="" />
            </div>

        </div>
        <br />
        <div class="form-group row row_design">

            <div class="col-sm-2 col-sm-offset-9">
                <button type="submit" class="btn btn-success" data-bind="enable: IsValid" data-toggle="modal" data-target="#myModal">Submit</button>
            </div>
        </div>
    </div>
    <div class="form-group">
        <div id="successModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Response</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p id="successModalText"></p>
                        <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Confirmation</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p>Do you want to add this Land Information?</p>
                        <button data-bind="click: SaveLandInfo" class="btn btn-success" data-dismiss="modal">Yes</button>
                        <button type="button" class="btn btn-success" data-dismiss="modal">No</button>

                    </div>
                    <div class="modal-footer">
                        @*<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>*@
                    </div>
                </div>

            </div>
        </div>
    </div>

</div>

Finix.UI/Areas/ATM/Views/AgriculturalInfo/AllAgriculturalLands.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Finix.ATM.DTO.AgriculturalLandInfoDto>
@{
    ViewBag.Title = "All Agricultural Lands";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
    var jss = new System.Web.Script.Serialization.JavaScriptSerializer();
    var pageDataJson = jss.Serialize(Model);
    var UPsJson = jss.Serialize(ViewBag.UPs);
    var WardsJson = jss.Serialize(ViewBag.Wards);
}

@*<h2>All Agricultural Lands</h2>*@
<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<link href="~/Content/PagedList.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/AgriculturalInfo/AgriculturalLandList.js"></script>



<script>
    var pageData = JSON.parse('@Html.Raw(pageDataJson)');
    var ups = JSON.parse('@Html.Raw(UPsJson)');
    var wards = JSON.parse('@Html.Raw(WardsJson)');
    var locationid = '@ViewBag.LocationId'
    var up = '@ViewBag.UP'
    
</script>




    <div class="panel-body rm">
        <div class="container-fluid" id="activeList">
            <div class="form-group row row_design">
                <div class="col-sm-2 col-sm-offset-10">
                    <button type="submit" class="btn btn-deepgreen" data-bind="click:AddNew">Add New</button>
                </div>
            </div>
            <br/>
            @using (Ajax.BeginForm("AllAgriculturalLands", "AgriculturalInfo", null))
            {


                <div class="form-group row row_design">
                    <div class="col-sm-2 col-sm-offset-1">
                        <label class="control-label">UP Name :</label>
                    </div>
                    <div class="col-sm-3">
                       
                            <select type="text" class="form-control" data-bind="options:UPs, value: UP, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>

                    </div>
                    <div class="col-sm-2">
                        <label class="control-label">Ward Name :</label>
                    </div>
                    <div class="col-sm-3">
                      
                            <select type="text" class="form-control" data-bind="options:Wards, value:LocationID, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>

                    </div>

                </div>
                        <br />
                                <div class="form-group row row_design">

                                    <div class="col-sm-offset-10">
                                        <button type="submit" class="btn btn-deepgreen">Search</button>
                                    </div>
                                </div>
            }
            <hr class="horizontal">

            <div class="panel">
                <br />
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="headcolor">
                                <tr>
                                    <th>Crop Season</th>
                                    <th>Location</th>
                                    <th>Crop Name</th>
                                    <th>Production</th>
                                    <th>Is Affected Before</th>
                                    <th>Affected Year</th>
                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody data-bind="foreach:PageData">
                                <tr>
                                    <td class="center" data-bind="text: CropSeasonName"></td>
                                    <td class="center" data-bind="text: LocationName "></td>
                                    <td class="center" data-bind="text: CropName "></td>
                                    <td class="center" data-bind="text: Production "></td>
                                    <td class="center"><input type="checkbox" data-bind="checked: AffectedBefore,enable:false" /></td>
                                    <td class="center" data-bind="text: AffectedYear"></td>
                                    <td class="center">
                                        <button type="button" data-bind='click: $parent.Edit' title="Edit">
                                            <span class="glyphicon glyphicon-edit"></span>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                    <div class="pagination-centered">
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("AllAgriculturalLands",
                                                        new
                                                        {
                                                            page,
                                                            sortOrder = ViewBag.CurrentSort,
                                                            up = ViewBag.UP,
                                                            locationid = ViewBag.LocationId

                                                        }))
                    </div>
                </div>
            </div>


        </div>



    </div>

Finix.UI/Areas/ATM/Views/AgriculturalInfo/CropCalendar.cshtml
@{
    ViewBag.Title = "Crop Calendar";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/AgriculturalInfo/CropCalendar.js"></script>

<div class="panel-body rm" id="divLandUse">
    <br />
    <div class="container-fluid">
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">UP<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-6" data-bind="validationElement: ParentLocationId">
                <select type="text" class="form-control" data-bind="options:ParentLocations, value:ParentLocationId, optionsCaption:'Select Thana', optionsValue:'Id', optionsText: 'LocationName'"></select>
            </div>

        </div>
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Location <span class="required">*</span> :</label>
            </div>
            <div class="col-sm-6" data-bind="validationElement: LocationId">
                <select type="text" class="form-control" data-bind="options:Locations, value:LocationId, optionsCaption:'Select UP', optionsValue:'Id', optionsText: 'LocationName'"></select>
            </div>

        </div>
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Crop Name<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-6">
                <select type="text" class="form-control" data-bind="options:Crops, value:CropId, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'CropName'"></select>
            </div>
        </div>
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Start Month<span class="required">*</span> :</label>
            </div>
                <div class="col-sm-6">
                    <select type="text" class="form-control" data-bind="options:Months, value:StartMonthId, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'EnglishName'"></select>
                </div>
           </div>
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">End Month<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-6">
                <select type="text" class="form-control" data-bind="options:Months, value:EndMonthId, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'EnglishName'"></select>
            </div>           
        </div>
        <br />
        <div class="form-group row row_design">

            <div class="col-sm-2 col-sm-offset-9">
                <button type="submit" class="btn btn-success" data-bind="enable: IsValid" data-toggle="modal" data-target="#myModal">Submit</button>
            </div>
        </div>
    </div>

    <div class="form-group">
        <div id="successModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Response</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p id="successModalText"></p>
                        <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Confirmation</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p>Do you want to add this Item to Calendar?</p>
                        <button data-bind="click: SaveCropCalendar" class="btn btn-success" data-dismiss="modal">Yes</button>
                        <button type="button" class="btn btn-success" data-dismiss="modal">No</button>

                    </div>
                    <div class="modal-footer">
                        @*<button type="button" class="btn btn-default" data-dismiss="modal">Close</button>*@
                    </div>
                </div>

            </div>
        </div>
    </div>

    <hr />
    <div class="panel">
        <div class="panel-heading">
            <header>Crop Calendar</header>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="headcolor">
                        <tr>
                            <th>Crop Name</th>
                            <th>UP Name</th>
                            <th>Jan</th>
                            <th>Feb</th>
                            <th>Mar</th>
                            <th>Apr</th>
                            <th>May</th>
                            <th>Jun</th>
                            <th>Jul</th>
                            <th>Aug</th>
                            <th>Sep</th>
                            <th>Oct</th>
                            <th>Nov</th>
                            <th>Dec</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach:Mappings">
                        <tr>
                            <td class="center" data-bind="text: CropName"></td>
                            <td class="center" data-bind="text: LocationName"></td>
                            <td class="center" data-bind="css: January"></td>
                            <td class="center" data-bind="css: February"></td>
                            <td class="center" data-bind="css: March"></td>
                            <td class="center" data-bind="css: April"></td>
                            <td class="center" data-bind="css: May"></td>
                            <td class="center" data-bind="css: June"></td>
                            <td class="center" data-bind="css: July"></td>
                            <td class="center" data-bind="css: August"></td>
                            <td class="center" data-bind="css: September"></td>
                            <td class="center" data-bind="css: October"></td>
                            <td class="center" data-bind="css: November"></td>
                            <td class="center" data-bind="css: December"></td>
                            <td class="center">
                                <button type="button" title="Edit" data-bind='click: $parent.editData'>
                                    <span class="glyphicon glyphicon-edit"></span>
                                </button>

                            </td>
                        </tr>
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>