Finix.UI/Areas/ATM/Controllers/SettingsController.cs
using Finix.ATM.DTO;
using Finix.ATM.Facade;
using Finix.ATM.Infrastructure;
using System;
using System.Collections.Generic;
using System.Globalization;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Finix.UI.Areas.ATM.Controllers
{
    public class SettingsController : Controller
    {
        private readonly LocationFacade _facadelocation = new LocationFacade();
        private readonly EnumFacade _enums = new EnumFacade();
        private readonly HouseHoldFacade _facade = new HouseHoldFacade();
        // GET: ATM/Settings


        #region Hazard Setup
        public ActionResult HazardSetup()
        {
            return View();
        }
        public ActionResult SaveHazard(HazardDto dto)
        {
            var result = _facadelocation.SaveHazards(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult AllHazards()
        {
            var data = _facadelocation.GetHazards();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult AllHazardsByLocation(long? locationid)
        {
            var data = _facadelocation.AllHazardByLocation(locationid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Elements
        public ActionResult ElementSetup()
        {
            return View();
        }

        public ActionResult AllElements(string sortOrder, string searchString, long? up, long? locationid, int page = 1, int pageSize = 20)
        {
           
            ViewBag.SearchString = searchString;
            ViewBag.CurrentSort = sortOrder;
            if (locationid != null)
                ViewBag.LocationId = (long)locationid;
            if (up != null)
                ViewBag.UP = (long)up;
            ViewBag.UPs =   _facadelocation.GetLocationsByLevel(LocationLevel.UP,null);
            ViewBag.Wards = _facadelocation.GetLocationsByLevel(LocationLevel.Ward,up);


            var data = _facadelocation.ElementList(pageSize, page, searchString, locationid);
            return View(data);
        }

        public ActionResult getElementById(long id)
        {
            var data = _facadelocation.GetElementById(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveElement(ElementDto dto)
        {
            var result = _facadelocation.SaveElements(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult ElementType()
        {
            return View();
        }
        public ActionResult SaveElementType(ElementTypeDto dto)
        {
            var result = _facadelocation.SaveElementType(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getElementTypes()
        {
            var data = _facadelocation.GetElementTypes();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getLocationsByLevel(LocationLevel level, long? parent)
        {
            var data = _facadelocation.GetLocationsByLevel(level,parent);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        
        #endregion
        
        #region Indicators

        public ActionResult IndicatorType()
        {
            return View();
        }
        public ActionResult SaveIndicatorType(IndicatorTypeDto dto)
        {
            var result = _facadelocation.SaveIndicatorType(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult getIndicatorPrimaryGroups()
        {
            var data = _enums.GetIndicatorPrimaryGroups();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getIndicatorTypes()
        {
            var data = _facadelocation.GetAllIndicatorTypes();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetIndicatorsByType(long typeid)
        {
            var data = _facadelocation.GetAllIndicatorsByType(typeid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult Indicators()
        {
            return View();
        }
        public ActionResult SaveIndicator(List<IndicatorsDto> dto)
        {
            var result = _facadelocation.SaveIndicators(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getIndicators()
        {
            var data = _facadelocation.GetAllIndicators();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        #endregion

        public ActionResult Sensitivity()
        {
            return View();
        }

        public ActionResult Exposure()
        {
            return View();
        }

       
        public ActionResult IndictorEvaluations()
        {
            return View();
        }
        

        #region Locations

        public ActionResult AllLocations(string sortOrder, string currentFilter, string searchString, long? up, long? locationid, int page = 1, int pageSize = 20)
        {

            ViewBag.SearchString = searchString;
            ViewBag.CurrentSort = sortOrder;
            if (locationid != null)
                ViewBag.LocationId = (long)locationid;
            if (up != null)
                ViewBag.UP = (long)up;
            ViewBag.UPs = _facadelocation.GetLocationsByLevel(LocationLevel.UP, null);
            ViewBag.Wards = _facadelocation.GetLocationsByLevel(LocationLevel.Ward, up);


            var data = _facadelocation.LocationList(pageSize, page, searchString, up, locationid);
            return View(data);
        }
        public ActionResult LocationSetup()
        {
            return View();
        }
        public ActionResult SaveLocation(LocationDto dto)
        {
            var result = _facadelocation.SaveLocations(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getLocationLevel()
        {
            var data = _enums.GetLocationLevels();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
       
        public ActionResult getParents(LocationLevel level)
        {
            var data = _facadelocation.GetParents(level);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult getLocationById(long id)
        {
            var data = _facadelocation.GetLocationById(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region Element At Risk
        public ActionResult ElementAtRisk()
        {
            return View();
        }
        public ActionResult SaveElementAtRisk(ElementAtRiskDto dto)
        {
            var result = _facadelocation.SaveElemntAtRisk(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult getElementsByLocation(long? locationid)
        {
            var data = _facadelocation.GetElements(locationid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getAllElementsAtRisk()
        {
            var data = _facadelocation.GetAllElementsAtRisk();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion


        #region Water Sources
        public ActionResult getAllWaterSource()
        {
            var data = _facadelocation.GetAllWaterSource();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Source Of Fund
        public ActionResult getAllSourceOfFund()
        {
            var data = _facadelocation.GetAllFundSource();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Support Type
        public ActionResult getAllSupportType()
        {
            var data = _facadelocation.GetAllSupportTypes();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Ethnic Minorty
        public ActionResult getAllEthnicMinority()
        {
            var data = _facadelocation.GetAllEthnicMinority();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        public ActionResult Diagram()
        {
            return View();
        }


        public ActionResult DisastersAndClimateChange()
        {
            return View();
        }

        public ActionResult getGenderList()
        {
            var data = _enums.GetGenders();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        #region Crops
        public ActionResult Crops()
        {
            return View();
        }

        public ActionResult SaveCrop(CropsDto dto)
        {
            var result = _facade.SaveCrop(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getCrops()
        {
            var data = _facade.GetCrops();
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        #endregion

        #region CultivationSeason
        public ActionResult CultivationSeason()
        {
            return View();
        }

        public ActionResult SaveCultivationSeason(CropSeasonDto dto)
        {
            var result = _facade.SaveCultivationSeason(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getMonths()
        {
            var data = _facade.GetMonths();

Finix.UI/Areas/ATM/Views/Settings/AllElements.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Finix.ATM.DTO.ElementDto>
@{
    ViewBag.Title = "All Elements";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
    var jss = new System.Web.Script.Serialization.JavaScriptSerializer();
    var pageDataJson = jss.Serialize(Model);
    var UPsJson = jss.Serialize(ViewBag.UPs);
    var WardsJson = jss.Serialize(ViewBag.Wards);
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<link href="~/Content/PagedList.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/Settings/ElementList.js"></script>

@*<h2>All Elements</h2>*@


<script>
    var pageData = JSON.parse('@Html.Raw(pageDataJson)');
    var ups = JSON.parse('@Html.Raw(UPsJson)');
    var wards = JSON.parse('@Html.Raw(WardsJson)');
    var locationid = '@ViewBag.LocationId'
    var up = '@ViewBag.UP'
    var searchString = '@ViewBag.SearchString'
</script>



<div class="panel-body rm">
   
        <div class="container-fluid"  id="activeList">
          
                   
                        <div class="form-group row row_design">
                            <div class="col-sm-2 col-sm-offset-10">
                                <button type="submit" class="btn btn-deepgreen" data-bind="click:AddNew">Add New Element</button>
                            </div>
                        </div>
            <br/>
                        @using (Ajax.BeginForm("AllElements", "Settings", null))
                        {
                            <div class="form-group row row_design">
                                <div class="col-sm-offset-1 col-sm-2">
                                    <label class="control-label">Name :</label>
                                </div>
                                <div class="col-sm-3">
                                    <input type="text" name="searchString" class="form-control" id="searchString" placeholder="Name" value="@(ViewBag.SearchString ?? String.Empty)">
                                </div>

                            </div>

                                <div class="form-group row row_design">
                                    <div class="col-sm-2 col-sm-offset-1">
                                        <label class="control-label">UP Name :</label>
                                    </div>
                                    <div class="col-sm-3">                                       
                                            <select type="text" class="form-control" data-bind="options:UPs, value: UP, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>                                  
                                    </div>
                                    <div class="col-sm-2">
                                        <label class="control-label">Ward Name :</label>
                                    </div>
                                    <div class="col-sm-3">                                      
                                            <select type="text" class="form-control" data-bind="options:Wards, value:LocationID, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>

                                    </div>

                                </div>
                                <br />
                                <div class="form-group row row_design">

                                    <div class="col-sm-2 col-sm-offset-10">
                                        <button type="submit" class="btn btn-deepgreen">Search</button>
                                    </div>
                                </div>
                        }
                        <hr class="horizontal">
                        <div class="panel">
                            <br/>
                            <div class="panel-body">
                                <div class="table-responsive">
                                    <table class="table table-striped table-bordered">
                                        <thead class="headcolor">
                                            <tr>
                                                <th> Name </th>
                                                <th> Type </th>
                                                <th> Location</th>
                                                <th> Details </th>
                                                <th> Action </th>
                                            </tr>
                                        </thead>

                                        <tbody data-bind="foreach:PageData">
                                            <tr>
                                                <td class="center" data-bind="text: Name"></td>
                                                <td class="center" data-bind="text: ElementTypeName "></td>
                                                <td class="center" data-bind="text: LocationName "></td>
                                                <td class="center" data-bind="text: Details"></td>

                                                <td class="center">
                                                    <button type="button" data-bind='click: $parent.Edit' title="Edit">
                                                        <span class="glyphicon glyphicon-edit"></span>
                                                    </button>
                                                </td>
                                            </tr>
                                        </tbody>
                                    </table>

                                </div>
                                <div class="pagination-centered">
                                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                                    @Html.PagedListPager(Model, page => Url.Action("AllElements",
                                                        new
                                                        {
                                                            page,
                                                            sortOrder = ViewBag.CurrentSort,
                                                            searchString = ViewBag.SearchString,
                                                            up = ViewBag.UP,
                                                            locationid = ViewBag.LocationId

                                                        }))
                                </div>
                            </div>

                        </div>
                    
             
        </div>
  

</div>

Finix.UI/Areas/ATM/Views/Settings/AllLocations.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Finix.ATM.DTO.LocationDto>
@{
    ViewBag.Title = "All Locations";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
    var jss = new System.Web.Script.Serialization.JavaScriptSerializer();
    var pageDataJson = jss.Serialize(Model);
    var UPsJson = jss.Serialize(ViewBag.UPs);
    var WardsJson = jss.Serialize(ViewBag.Wards);
}
<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<link href="~/Content/PagedList.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/Settings/LocationList.js"></script>


@*<h2>All Locations</h2>*@

<script>
    var pageData = JSON.parse('@Html.Raw(pageDataJson)');
    var ups = JSON.parse('@Html.Raw(UPsJson)');
    var wards = JSON.parse('@Html.Raw(WardsJson)');
    var locationid = '@ViewBag.LocationId'
    var up = '@ViewBag.UP'
    var searchString = '@ViewBag.SearchString'
</script>




    <div class="panel-body rm">
        <div class="container-fluid" id="activeList">


            <div class="form-group row row_design">

                <div class="col-sm-2 col-sm-offset-10">
                    <button type="submit" class="btn btn-deepgreen" data-bind="click:AddNew">Add New Location</button>
                </div>
            </div>
            <br/>

            @using (Ajax.BeginForm("AllLocations", "Settings", null))
            {
                <div class="form-group row row_design">
                    <div class="col-sm-offset-1 col-sm-2">
                        <label class="control-label">Name :</label>
                    </div>
                    <div class="col-sm-3" data-bind="validationElement: LocationName">
                        <input type="text" name="searchString" class="form-control" id="searchString" placeholder="Name" value="@(ViewBag.SearchString ?? String.Empty)">
                    </div>

                </div>

                                <div class="form-group row row_design">
                                    <div class="col-sm-2 col-sm-offset-1">
                                        <label class="control-label">UP Name :</label>
                                    </div>
                                    <div class="col-sm-3" data-bind="validationElement: UP">                                      
                                            <select type="text" name="up" class="form-control" data-bind="options:UPs, value: UP, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>

                                    </div>
                                    <div class="col-sm-2">
                                        <label class="control-label">Ward Name :</label>
                                    </div>
                                    <div class="col-sm-3" data-bind="validationElement: LocationID">
                                           <select type="text" name="locationid" class="form-control" data-bind="options:Wards, value:LocationID, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>

                                    </div>

                                </div>
                                <br />
                                <div class="form-group row row_design">

                                    <div class="col-sm-2 col-sm-offset-10">
                                        <button type="submit" class="btn btn-deepgreen">Search</button>
                                    </div>
                                </div>
            }
            <hr class="horizontal">

            <div class="panel">
                <br />
                <div class="panel-body">
                    <div class="table-responsive">
                        <table class="table table-striped table-bordered">
                            <thead class="headcolor">
                                <tr>
                                    <th>Location Name</th>
                                    <th>Level</th>
                                    <th>Parent</th>
                                    <th>GO Code</th>
                                    <th>Action</th>
                                </tr>
                            </thead>

                            <tbody data-bind="foreach:PageData">
                                <tr>
                                    <td class="center" data-bind="text:LocationName"></td>
                                    <td class="center" data-bind="text:LevelName"></td>
                                    <td class="center" data-bind="text:ParentName"></td>
                                    <td class="center" data-bind="text:Code"></td>
                                    <td class="center">
                                        <button type="button" data-bind='click: $parent.Edit' title="Edit">
                                            <span class="glyphicon glyphicon-edit"></span>
                                        </button>
                                    </td>
                                </tr>
                            </tbody>
                        </table>

                    </div>
                    <div class="pagination-centered">
                        Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                        @Html.PagedListPager(Model, page => Url.Action("AllLocations",
                                                        new
                                                        {
                                                            page,
                                                            sortOrder = ViewBag.CurrentSort,
                                                            searchString = ViewBag.SearchString,
                                                            up = ViewBag.UP,
                                                            locationid = ViewBag.LocationId,
                                                            currentFilter = ViewBag.CurrentFilter

                                                        }))
                    </div>
                </div>
            </div>



        </div>

    </div>

Finix.UI/Areas/ATM/Views/Settings/Crops.cshtml
@{
    ViewBag.Title = "Crops";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/Settings/Crops.js"></script>


<div class="panel-body rm" id="divCrop">
    <br />
    <div class="container-fluid">
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Crop Name<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-6" data-bind="validationElement:CropName">
                <input type="text" class="form-control" data-bind="value:CropName,valueUpdate: 'keyup'" placeholder="Type a Crop Name" value="">
            </div>

        </div>

        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Details :</label>
            </div>
            <div class="col-sm-6" data-bind="validationElement:Details">
                <textarea type="text" class="form-control" data-bind="value:Details,valueUpdate: 'keyup'" placeholder="Type Crop Details" value=""></textarea>
            </div>

        </div>

        <br />
        <div class="form-group row row_design">

            <div class="col-sm-2 col-sm-offset-9">
                <button type="submit" class="btn btn-success" data-bind="enable: IsValid" data-toggle="modal" data-target="#myModal">Submit</button>
            </div>
        </div>
    </div>

    <hr />
    <div class="panel">
        <div class="panel-heading">
            <header>Crop List</header>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered" @*style="font-size: 11px "*@>
                    <thead class="headcolor">
                        <tr>
                            <th>Crop Name</th>
                            <th>Details</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach:Crops">
                        <tr>

                            <td class="center" data-bind="text:CropName"></td>
                            <td class="center" data-bind="text:Details"></td>

                            <td class="center">
                                <button type="button" data-bind='click: $parent.editCrop' title="Edit">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </button>

                            </td>

                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    <div class="form-group">
        <div id="successModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Response</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p id="successModalText"></p>
                        <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Confirmation</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p>Do you want to add this Crop?</p>
                        <button data-bind="click: SaveCrop" class="btn btn-success" data-dismiss="modal">Yes</button>
                        <button type="button" class="btn btn-success" data-dismiss="modal">No</button>

                    </div>
                    <div class="modal-footer">

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

Finix.UI/Areas/ATM/Views/Settings/ElementList.cshtml
@model PagedList.IPagedList<Finix.ATM.DTO.ElementDto>
@using PagedList.Mvc;

@{
    ViewBag.Title = "ElementList";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
    var jss = new System.Web.Script.Serialization.JavaScriptSerializer();
    var userInfoJson = jss.Serialize(Model);
}



<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<link href="~/Content/PagedList.css" rel="stylesheet" />
<script>
    var userInfo = JSON.parse('@Html.Raw(userInfoJson)');
</script>


<div class="panel-body rm">
    <br />
    <div class="container-fluid">
@*@using (Ajax.BeginForm("SearchElementInformation", "Settings", null))
    {*@
        <div class="form-group row row_design">
            <div class="col-sm-offset-1 col-sm-2">
                <label class="control-label">UP Name<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-3">
                <input type="text" class="form-control" placeholder="UP Name" value="@ViewBag.CurrentFilter"/>
            </div>

            <div class="col-sm-2">
                <label class="control-label">Ward Name<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-3">
                <input type="text" class="form-control" placeholder="Ward Name" value="@ViewBag.CurrentFilter" />
            </div>

        </div>


        <br />
        <div class="form-group row row_design">

            <div class="col-sm-2 col-sm-offset-10">
                <button type="submit" class="btn btn-deepgreen">Search</button>
            </div>
        </div>



        <hr />
        <div class="panel">
            <div class="panel-heading">
                <header>Element List</header>
            </div>
            <div class="panel-body">

                <br />
                <div class="form-group row row_design">

                    <div class="col-sm-2 col-sm-offset-9">
                        <button type="submit" class="btn btn-primary">Add New</button>
                    </div>
                </div>
                <br />
                <div class="table-responsive">
                    <table class="table table-striped table-bordered" @*style="font-size: 11px "*@>
                        <thead class="headcolor">
                            <tr>
                                <th>UP Name</th>
                                <th>Ward Name</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody @*data-bind="foreach:LeaveApplication"*@>
                            <tr>

                                <td class="center"></td>
                                <td class="center"></td>
                                <td class="center">
                                    <button type="button" @*data-bind='click: $parent.SendMessage'*@ title="Edit">
                                        <span class="glyphicon glyphicon-edit"></span>
                                    </button>

                                </td>

                            </tr>
                        </tbody>
                    </table>

                    <div class="pagination-centered">
                        @*Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount

                        @Html.PagedListPager(Model, page => Url.Action("SearchElementInformation",
                            new { page, sortOrder = ViewBag.CurrentSort, currentFilter = ViewBag.CurrentFilter }))*@

                    </div>
                </div>
            </div>
        </div>
@*}*@
    </div>
</div>