Finix.UI/Areas/ATM/Controllers/HouseholdController.cs
using Finix.ATM.DTO;
using Finix.ATM.Facade;
using Finix.ATM.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using Microsoft.Reporting.WebForms;
using System.Web.Mvc;
using System.IO;

namespace Finix.UI.Areas.ATM.Controllers
{
    public class HouseholdController : Controller
    {
        private readonly HouseHoldFacade _facade = new HouseHoldFacade();
        private readonly LocationFacade _facadelocation = new LocationFacade();
        private readonly EnumFacade _enums = new EnumFacade();
        // GET: ATM/Household
        #region Energy Sources
        public ActionResult EnergySource()
        {
            return View();
        }
        public ActionResult SaveEnergySource(EnergySourceDto dto)
        {
            var result = _facade.SaveEnergySource(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getEnergySources()
        {
            var data = _facade.GetEnergySources();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Materails
        public ActionResult Material()
        {
            return View();
        }
        public ActionResult SaveMaterial(MaterialDto dto)
        {
            var result = _facade.SaveMaterial(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getMaterials()
        {
            var data = _facade.GetMaterials();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Building Part
        //public ActionResult Material()
        //{
        //    return View();
        //}
        //public ActionResult SaveMaterial(MaterialDto dto)
        //{
        //    var result = _facade.SaveMaterial(dto, SessionHelper.UserProfile.UserId);
        //    return Json(result, JsonRequestBehavior.AllowGet);
        //}
        public ActionResult getBuildingParts()
        {
            var data = _facade.GetBuildingParts();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        public ActionResult HouseholdActivityTracking()
        {
            return View();
        }

        public ActionResult QuestionAboutHousehold()
        {
            return View();
        }

        public ActionResult AboutBuilding()
        {
            return View();
        }

        public ActionResult QuestionAboutFood()
        {
            return View();
        }

        public ActionResult QuestionAboutHealth()
        {
            return View();
        }

        public ActionResult EnergyAndFarming()
        {
            return View();
        }

        #region House Hold Informations
        public ActionResult HouseholdInformation()
        {
            return View();
        }
        public ActionResult SaveHHBasicInfo(HouseHoldInformationDto dto)
        {
            var result = _facade.SaveHHBasicInfo(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveHHSurveyInfo(HouseHoldSurveyAdministrationDto dto)
        {
            var result = _facade.SaveHHSurveyInfo(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveHHBuildingInfo(HouseHoldBuildingDto dto)
        {
            var result = _facade.SaveHHBuildingInfo(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveHHFoodInfo(HouseHoldFoodDto dto)
        {
            var result = _facade.SaveHHFoodInfo(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveHHHealthInfo(HouseHoldHealthDto dto)
        {
            var result = _facade.SaveHHHealthInfo(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveHHLandAsset(HouseHoldLandAssetDto dto)
        {
            var result = _facade.SaveHHLandAsset(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveHHEnergyInfo(HouseHoldEnergyDto dto)
        {
            var result = _facade.SaveHHEnergyInfo(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult HouseholdList(string sortOrder, string currentFilter, string searchString, long? ownership, long? occupation, long? distid, long? upazilaid, long? up, long? locationid, bool? savings, bool? womenheaded, bool? proximity, bool? ethnicminority, bool? adolsentmother, bool? disable, bool? migrated, bool? embankment, double? lowerlimit, double? upperlimit, int? lowerage, int? upperage, int page = 1, int pageSize = 20)
        {
            ViewBag.SearchString = searchString; 
            ViewBag.CurrentSort = sortOrder;

            if (distid != null)
                ViewBag.DistId = (long)distid;
            if (upazilaid != null)
                ViewBag.UpazilaId = (long)upazilaid;
            if (ownership != null)
                ViewBag.UP = (long)ownership;
            if (locationid != null)
                ViewBag.LocationId = (long)locationid;

            if (ownership != null)
                ViewBag.Ownership = (long)ownership;
            if (occupation != null)
                ViewBag.Occupation = (long)occupation;

            if (lowerlimit != null)
                ViewBag.LowerLimit = (long)lowerlimit;
            if (upperlimit != null)
                ViewBag.UpperLimit = (long)upperlimit;
            if (lowerage != null)
                ViewBag.LowerAge = (long)lowerage;
            if (upperage != null)
                ViewBag.UpperAge = (long)upperage;


            if (savings != null)
                ViewBag.Savings = (bool)savings;
            if (womenheaded != null)
                ViewBag.WomenHeaded = (bool)womenheaded;
            if (proximity != null)
                ViewBag.Proximity = (bool)proximity;
            if (ethnicminority != null)
                ViewBag.EthnicMinority = (bool)ethnicminority;
            if (adolsentmother != null)
                ViewBag.AdolsentMother = (bool)adolsentmother;
            if (disable != null)
                ViewBag.Disable = (bool)disable;
            if (migrated != null)
                ViewBag.Migrated = (bool)migrated;
            if (embankment != null)
                ViewBag.Embankment = (bool)embankment;



            ViewBag.Districts = _facadelocation.GetLocationsByLevel(LocationLevel.District, null);
            ViewBag.Upazilas = _facadelocation.GetLocationsByLevel(LocationLevel.Upazila, distid);
            ViewBag.UPs = _facadelocation.GetLocationsByLevel(LocationLevel.UP, upazilaid);
            ViewBag.Wards = _facadelocation.GetLocationsByLevel(LocationLevel.Ward, up);

            var data = _facade.householdList(pageSize, page, searchString, ownership, occupation,  distid, upazilaid, up,  locationid, savings, womenheaded, proximity, ethnicminority,adolsentmother, disable,  migrated, embankment,  lowerlimit, upperlimit, lowerage, upperage);
            return View(data);
        }

        public ActionResult HouseholdWaitingList(string sortOrder, string currentFilter, string searchString, long? up, long? locationid, int page = 1, int pageSize = 20)
        {
            ViewBag.SearchString = searchString;
            ViewBag.CurrentSort = sortOrder;
            if (locationid != null)
                ViewBag.LocationId = (long)locationid;
            if (up != null)
                ViewBag.UP = (long)up;
            ViewBag.UPs = _facadelocation.GetLocationsByLevel(LocationLevel.UP, null);
            ViewBag.Wards = _facadelocation.GetLocationsByLevel(LocationLevel.Ward, up);


            var data = _facade.householdWaitingList(pageSize, page, searchString, up, locationid);
            return View(data);
        }

        public ActionResult GetHouseHoldBasicData(long hhid)
        {
            var data = _facade.LoadHouseHoldBasicInfo(hhid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult SaveHHMember(HouseHoldMembersDto dto)
        {
            var result = _facade.SaveHHmember(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult SaveHHDisaster(HouseHoldDisastersDto dto)
        {
            var result = _facade.SaveHHDisasters(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetHouseHoldmemberData(long hhid)
        {
            var data = _facade.LoadHouseHoldMemberInfo(hhid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetHouseHoldDisaterData(long hhid)
        {
            var data = _facade.LoadHouseHoldDisasterInfo(hhid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetMemberDataById(long memid)
        {
            var data = _facade.getMemberInfo(memid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetHouseHoldSurveyData(long hhid)
        {
            var data = _facade.LoadHouseHoldSurveyInfo(hhid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        public ActionResult GetHouseHoldBuildingData(long hhid)
        {
            var data = _facade.LoadHouseHoldBuildingInfo(hhid);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

Finix.UI/Areas/ATM/Views/Household/EnergySource.cshtml
@{
    ViewBag.Title = "EnergySource";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/HouseHold/EnergySource.js"></script>

<div class="panel-body rm" id="divEnergy">
    <br />
    <div class="container-fluid">
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Source Name<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-6" data-bind="validationElement:SourceName">
                <input type="text" class="form-control" data-bind="value:SourceName,valueUpdate: 'keyup'" placeholder="Type a Name" value="">
            </div>

        </div>



        <br />
        <div class="form-group row row_design">

            <div class="col-sm-2 col-sm-offset-9">
                <button type="submit" class="btn btn-success" data-bind="enable: IsValid" data-toggle="modal" data-target="#myModal">Submit</button>
            </div>
        </div>
    </div>

    <hr />
    <div class="panel">
        <div class="panel-heading">
            <header>List of Enegry Sources</header>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered" @*style="font-size: 11px "*@>
                    <thead class="headcolor">
                        <tr>
                            <th>Source Name</th>

                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach:Sources">
                        <tr>

                            <td class="center" data-bind="text:SourceName"></td>

                            <td class="center">
                                <button type="button" data-bind='click: $parent.editEnergySource' title="Edit">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </button>

                            </td>

                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    <div class="form-group">
        <div id="successModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Response</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p id="successModalText"></p>
                        <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Confirmation</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p>Do you want to add this Type?</p>
                        <button data-bind="click: SaveEnergySource" class="btn btn-success" data-dismiss="modal">Yes</button>
                        <button type="button" class="btn btn-success" data-dismiss="modal">No</button>

                    </div>
                    <div class="modal-footer">

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

Finix.UI/Areas/ATM/Views/Household/HouseholdWaitingList.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Finix.ATM.DTO.HouseHoldListDto>
@{
    ViewBag.Title = "Household Analysis";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
    var jss = new System.Web.Script.Serialization.JavaScriptSerializer();
    var pageDataJson = jss.Serialize(Model);
    var UPsJson = jss.Serialize(ViewBag.UPs);
    var WardsJson = jss.Serialize(ViewBag.Wards);
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<link href="~/Content/PagedList.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/HouseHold/HHWaitingList.js"></script>

<script>
    var pageData = JSON.parse('@Html.Raw(pageDataJson)');
    var ups = JSON.parse('@Html.Raw(UPsJson)');
    var wards = JSON.parse('@Html.Raw(WardsJson)');
    var locationid = '@ViewBag.LocationId'
    var up = '@ViewBag.UP'
    var searchString = '@ViewBag.SearchString'
</script>




<div class="panel-body rm" id="householdAnalysisList">
    <br />

    <div class="panel-body">
        <div class="container-fluid">
            @using (Ajax.BeginForm("HouseholdWaitingList", "Household", null))
            {
                <div class="form-group row row_design">
                    <div class="col-sm-offset-1 col-sm-2">
                        <label class="control-label">HH No.<span class="required">*</span> :</label>
                    </div>
                    <div class="col-sm-3">
                        <input type="text" name="searchString" class="form-control"  id="searchString" placeholder="HH No." value="@(ViewBag.SearchString ?? String.Empty)" />
                    </div>

                </div>

                <div class="form-group row row_design">
                    <div class="col-sm-offset-1 col-sm-2">
                        <label class="control-label">UP<span class="required">*</span> :</label>
                    </div>
                    <div class="col-sm-3">
                        <select type="text" class="form-control" name="up" data-bind="options:UPs, value: UP, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>
                    </div>
                    <div class="col-sm-2">
                        <label class="control-label">Ward<span class="required">*</span> :</label>
                    </div>
                    <div class="col-sm-3" >
                        <select type="text" class="form-control" name="locationid" data-bind="options:Wards, value:LocationID, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>
                    </div>
                </div>



                <br />
                <div class="form-group row row_design">

                    <div class="col-sm-2 col-sm-offset-10">
                        <button type="submit" class="btn btn-deepgreen" >Search</button>
                    </div>
                </div>
            }
        </div>

        <div class="form-group row row_design">
            <div class="col-sm-offset-1 col-sm-5">
                <button type="submit" data-bind="click:Selection" class="btn btn-deepgreen">Select For Proposal</button>
            </div>
        </div>

        <hr />
        <div class="panel">
            <div class="panel-heading">
                <header>Household Waiting List</header>
            </div>
            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <thead class="headcolor">
                            <tr>
                                <th>Propose ?</th>
                                <th>HH No</th>
                                <th>Address</th>
                                
                            </tr>
                        </thead>
                        <tbody data-bind="foreach:pageData">
                            <tr>

                                <td class="center"><input type="checkbox" data-bind="checked:IsSelected" /></td>
                                <td class="center" data-bind="text:HouseHoldNo"></td>
                                <td class="center" data-bind="text:Address"></td>
                             </tr>
                        </tbody>
                    </table>
                </div>
                <div class="pagination-centered">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    @Html.PagedListPager(Model, page => Url.Action("HouseholdWaitingList",
                                                        new
                                                        {
                                                            page,
                                                            sortOrder = ViewBag.CurrentSort,
                                                            searchString = ViewBag.SearchString,
                                                            up = ViewBag.UP,
                                                            locationid = ViewBag.LocationId,
                                                            currentFilter = ViewBag.CurrentFilter
                                                        }))


                </div>
            </div>
        </div>
        
        <!--Start modal body>-->
        <div class="form-group">
            <div id="successModal" class="modal fade" role="dialog">
                <div class="modal-dialog modal-sm">
                    <!-- Modal content-->
                    <div class="modal-content">
                        <div class="modal-header">
                            <button type="button" class="close" data-dismiss="modal">&times;</button>
                            <h4 class="modal-title">Response</h4>
                        </div>
                        <div class="modal-body" align="center">
                            <p id="successModalText"></p>

                            <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>

                        </div>
                        <div class="modal-footer">
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

Finix.UI/Areas/ATM/Views/Household/ProposaledHHList.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Finix.ATM.DTO.HouseHoldListDto>
@{
    ViewBag.Title = "Household Analysis";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
    var jss = new System.Web.Script.Serialization.JavaScriptSerializer();
    var pageDataJson = jss.Serialize(Model);
    var UPsJson = jss.Serialize(ViewBag.UPs);
    var WardsJson = jss.Serialize(ViewBag.Wards);
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<link href="~/Content/PagedList.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/HouseHold/ProposedHouseHoldList.js"></script>


<script>
    var pageData = JSON.parse('@Html.Raw(pageDataJson)');
    var ups = JSON.parse('@Html.Raw(UPsJson)');
    var wards = JSON.parse('@Html.Raw(WardsJson)');
    var locationid = '@ViewBag.LocationId'
    var up = '@ViewBag.UP'
    var searchString = '@ViewBag.SearchString'
</script>

<div class="panel-body rm" id="divHH">
    <br />
    <div class="container-fluid">
        @using (Ajax.BeginForm("ProposaledHHList", "Household", null))
            {
            <div class="form-group row row_design">
                <div class="col-sm-offset-1 col-sm-2">
                    <label class="control-label">HH No.<span class="required">*</span> :</label>
                </div>
                <div class="col-sm-3">
                    <input type="text" name="searchString" class="form-control" id="searchString" placeholder="HH No." value="@(ViewBag.SearchString ?? String.Empty)" />
                </div>

            </div>

                <div class="form-group row row_design">
                    <div class="col-sm-offset-1 col-sm-2">
                        <label class="control-label">UP<span class="required">*</span> :</label>
                    </div>
                    <div class="col-sm-3">
                        <select type="text" class="form-control" name="up" data-bind="options:UPs, value: UP, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>
                    </div>
                    <div class="col-sm-2">
                        <label class="control-label">Ward<span class="required">*</span> :</label>
                    </div>
                    <div class="col-sm-3">
                        <select type="text" class="form-control" name="locationid" data-bind="options:Wards, value:LocationID, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>
                    </div>
                </div>


                <br />
                <div class="form-group row row_design">

                    <div class="col-sm-2 col-sm-offset-10">
                        <button type="submit" class="btn btn-deepgreen">Search</button>
                    </div>
                </div>
        }
    </div>

    <hr />
    <div class="panel">
        <div class="panel-heading">
            <header>Household List</header>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="headcolor">
                        <tr>
                            <th>Propose ?</th>
                            <th>HH No</th>
                            <th>Address</th>
                            <th>Grant Amount</th>
                            <th>Disbursed Amount</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach:PageData">
                        <tr>
                            <td class="center"><input type="checkbox" data-bind="checked:IsSelected" disabled /></td>
                            <td class="center" data-bind="text:HouseHoldNo"></td>
                            <td class="center" data-bind="text:Address"></td>
                            <td class="center" data-bind="text:GrantedAmount"></td>
                            <td class="center" data-bind="text:DisbursedAmount"></td>
                            <td class="center">
                                <button type="button" data-bind='click: $parent.RRAP' class="btn btn-default">
                                    HH RRAP
                                </button>
                                <button type="button" data-bind='click: $parent.Proposal,visible:!HaveIntervertion' class="btn btn-default">
                                    New Intervention
                                </button>
                                <button type="button" data-bind='click: $parent.Intervention' class="btn btn-default">
                                    Existing Intervention
                                </button>
                                <button type="button" data-bind='click: $parent.Disburse,visible:HaveIntervertion' class="btn btn-default">
                                    Disburse
                                </button>
                                <button type="button" data-bind='click: $parent.Scheme' class="btn btn-default">
                                    Implementation
                                </button>
                            </td>

                        </tr>
                    </tbody>
                </table>
            </div>
            <div class="pagination-centered">
                Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                @Html.PagedListPager(Model, page => Url.Action("ProposaledHHList",
                                                        new
                                                        {
                                                            page,
                                                            sortOrder = ViewBag.CurrentSort,
                                                            searchString = ViewBag.SearchString,
                                                            up = ViewBag.UP,
                                                            locationid = ViewBag.LocationId,
                                                            currentFilter = ViewBag.CurrentFilter
                                                        }))


            </div>
        </div>
    </div>
</div>

Finix.UI/Areas/ATM/Views/Household/VulnerableHHList.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Finix.ATM.DTO.HouseHoldPotentialImpactDto>
@{
    ViewBag.Title = "Household Analysis";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
    var jss = new System.Web.Script.Serialization.JavaScriptSerializer();
    var pageDataJson = jss.Serialize(Model);
    var UPsJson = jss.Serialize(ViewBag.UPs);
    
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<link href="~/Content/PagedList.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/HouseHold/VulnerableList.js"></script>

<script>
    var pageData = JSON.parse('@Html.Raw(pageDataJson)');
    var ups = JSON.parse('@Html.Raw(UPsJson)');
   
    var up = '@ViewBag.UP'
    var searchString = '@ViewBag.SearchString'
</script>




<div class="panel-body rm" id="householdAnalysisList">
    <br />

    <div class="panel-body">
        <div class="container-fluid">
            @using (Ajax.BeginForm("VulnerableHHList", "Household", null))
            {
                <div class="form-group row row_design">
                    <div class="col-sm-offset-1 col-sm-2">
                        <label class="control-label">Search By<span class="required">*</span> :</label>
                    </div>
                    <div class="col-sm-3" >
                        <input type="text" name="searchString" class="form-control" @*data-bind="value:HouseHoldNo,valueUpdate: 'keyup'"*@ id="searchString" placeholder="Search by HH No/Location Name" value="@(ViewBag.SearchString ?? String.Empty)" />
                    </div>
                    <div class="col-sm-2">
                        <label class="control-label">UP<span class="required">*</span> :</label>
                    </div>
                    <div class="col-sm-3" >
                        <select type="text" class="form-control" name="up" data-bind="options:UPs, value: UP, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>
                    </div>
                </div>

              
                <br />
                <div class="form-group row row_design">

                    <div class="col-sm-2 col-sm-offset-10">
                        <button type="submit" class="btn btn-deepgreen" @*data-bind="click:Search"*@ @*data-bind="enable: IsValid" data-toggle="modal" data-target="#myModal"*@>Search</button>
                    </div>
                </div>
            }
        </div>


        

        <hr />
        <div class="panel">

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <thead class="headcolor">
                            <tr>

                                <th>HH No.</th>
                                <th>Location</th>
                                <th>Vulnerability Score</th>
                               
                            </tr>
                        </thead>
                        <tbody data-bind="foreach:PageData">
                            <tr>
                                <td class="center" data-bind="text:HouseHoldNo"></td>
                                <td class="center" data-bind="text:LocationName"></td>
                                <td class="center" data-bind="text:VulnerabilityScore"></td>
                                
                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="pagination-centered">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    @Html.PagedListPager(Model, page => Url.Action("VulnerableHHList",
                                                        new
                                                        {
                                                            page,
                                                            sortOrder = ViewBag.CurrentSort,
                                                            searchString = ViewBag.SearchString,
                                                            up = ViewBag.UP,
                                                           currentFilter = ViewBag.CurrentFilter
                                                        }))


                </div>
            </div>
        </div>
    </div>
</div>