Finix.UI/Areas/ATM/Controllers/SchemeController.cs
using Finix.ATM.DTO;
using Finix.ATM.Facade;
using Finix.ATM.Infrastructure;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Finix.UI.Areas.ATM.Controllers
{
    public class SchemeController : Controller
    {
        private readonly SchemeFacade _facade = new SchemeFacade();
        private readonly LocationFacade _facadelocation = new LocationFacade();
        private readonly EnumFacade _enums = new EnumFacade();
        // GET: ATM/Scheme
        #region SchemeCategory
        public ActionResult SchemeCategory()
        {
            return View();
        }
        public ActionResult SaveSchemeCategory(SchemeCategoryDto dto)
        {
            var result = _facade.SaveSchemeCategory(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getSchemeCategories()
        {
            var data = _facade.GetSchemeCategories();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion

        #region Scheme Nature
        public ActionResult SchemeNature()
        {
            return View();
        }
        public ActionResult SaveSchemeNature(SchemeNatureDto dto)
        {
            var result = _facade.SaveSchemeNature(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }
        public ActionResult getSchemeNatures()
        {
            var data = _facade.GetSchemeNatures();
            return Json(data, JsonRequestBehavior.AllowGet);
        }
        #endregion


        public ActionResult ProposedHouseHoldList()
        {
            return View();
        }
        public ActionResult SchemeImplementation()
        {
            return View();
        }

        public ActionResult SchemeImplementationCRF()
        {
            return View();
        }

        public ActionResult SaveSchemeImplementation(SchemeInformationDto dto)
        {
            var result = _facade.SaveSchemePBCRG(dto, SessionHelper.UserProfile.UserId);
            return Json(result, JsonRequestBehavior.AllowGet);
        }

        public ActionResult GetSchemeData(long id)
        {
            var data = _facade.LoadSchemeInfo(id);
            return Json(data, JsonRequestBehavior.AllowGet);
        }

        public ActionResult CRFDashboard()
        {
            return View();
        }

        #region Scheme List
        //public ActionResult SchemeList()
        //{
        //    return View();
        //}

        public ActionResult SchemeList(string sortOrder, string currentFilter, string searchString, long? thana, long? up, int page = 1, int pageSize = 20)
        {

            ViewBag.SearchString = searchString;
            ViewBag.CurrentSort = sortOrder;
            if (up != null)
                ViewBag.UP = (long)up;
            if (thana != null)
                ViewBag.Thana = (long)thana;
            ViewBag.UPs = _facadelocation.GetLocationsByLevel(LocationLevel.UP, thana);
            ViewBag.Thanas = _facadelocation.GetLocationsByLevel(LocationLevel.Upazila, null);


            var data = _facade.SchemeList(pageSize, page, searchString, thana, up);
            return View(data);
        }

        //public ActionResult getHouseholdAnalysisInfoById(long id)
        //{
        //    var data = _facade.getHouseholdAnalysisInfoById(id);
        //    return Json(data, JsonRequestBehavior.AllowGet);
        //}

        #endregion

    }
}

Finix.UI/Areas/ATM/Views/Scheme/CRFDashboard.cshtml
@{
    ViewBag.Title = "CRFDashboard";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
}


<script src="~/Content/customassets/js/jquery-3.1.1.min.js"></script>
<script src="~/Content/customassets/js/highcharts.js"></script>
<script src="~/Content/customassets/js/exporting.js"></script>
<script src="~/Content/customassets/js/export-data.js"></script>
@*<script src="~/Areas/ATM/Scripts/Scheme/CRFDashboard.js"></script>*@
<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />


<style>
    .highcharts-credits {
        visibility: hidden !important;
    }

    .highcharts-exporting-group {
        visibility: hidden !important;
    }

    .label-default {
        font-size: 12px;
    }
</style>

<div class="panel-body rm" @*id="divCRFDash"*@>
    
    <div class="container-fluid">
        <div class="form-group row row_design">
           
            <div class="col-sm-offset-1 col-sm-1">
                <label class="control-label">Thana :</label>
            </div>
            <div class="col-sm-3" @*data-bind="validationElement: ThanaId"*@>
                <select type="text" class="form-control" @*data-bind="options:Thanas, value:ThanaId, optionsCaption:'Choose Upazila..', optionsValue:'Id', optionsText: 'LocationName'"*@></select>
            </div>

            <div class="col-sm-offset-1 col-sm-1">
                <label class="control-label">UP :</label>
            </div>
            <div class="col-sm-3" @*data-bind="validationElement: UPId"*@>
                <select type="text" class="form-control" @*data-bind="options:UPs, value:UPId, optionsCaption:'Choose Union..', optionsValue:'Id', optionsText: 'LocationName'"*@></select>
            </div>
        </div>
        <br/>
       
        <div class="panel" @*data-bind="visible:IsReady"*@>
            
            <div class="panel-body">

                <div class="row">
                    <div class="col-sm-12">

                        <div class="col-sm-6">
                            <div class="form-group row row_design">
                                <div class="col-sm-offset-1 col-sm-5">
                                    <label class="control-label">Beneficiary :</label>
                                </div>
                                <div class="col-sm-5" @*data-bind="validationElement: LocationName"*@>
                                    <span class="label label-default">24.07 HHs</span>
                                </div>
                            </div>
                            <div class="form-group row row_design">
                                <div class="col-sm-offset-1 col-sm-5">
                                    <label class="control-label">Proposals :</label>
                                </div>
                                <div class="col-sm-5" @*data-bind="validationElement: Locationlevels"*@>
                                    <span class="label label-default">8003</span>
                                </div>
                            </div>


                        </div>
                        <div class="col-sm-6">
                            <div class="form-group row row_design">
                                <div class="col-sm-offset-1 col-sm-5">
                                    <label class="control-label">Selected :</label>
                                </div>
                                <div class="col-sm-5" @*data-bind="validationElement: LocationName"*@>
                                    <span class="label label-default">6</span>
                                </div>
                            </div>
                            <div class="form-group row row_design">
                                <div class="col-sm-offset-1 col-sm-5">
                                    <label class="control-label">Disbursed :</label>
                                </div>
                                <div class="col-sm-5" @*data-bind="validationElement: Locationlevels"*@>
                                    <span class="label label-default">5000 (BDT)</span>
                                </div>
                            </div>

                        </div>


                    </div>
                </div>


            </div>
        </div>
        <hr />


        <div class="panel">
            <br />
            <div class="panel-body">

                <div class="form-group row row_design">
                    <div id="SectorWiseDisbursement" style="min-width: 310px; height: 400px; margin: 0 auto"></div>

                </div>
            </div>
        </div>

        <hr />
        <div class="panel">
            <br />
            <div class="panel-body">

                <div class="form-group row row_design">
                   
                        <div id="AmountDisbursed" style="min-width: 310px; height: 400px; max-width: 600px; margin: 0 auto"></div>

                </div>

            </div>
        </div>


    </div>

</div>



<script>


    // Build the chart
    Highcharts.chart('SectorWiseDisbursement', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: 'Sector Wise Disbursement'
        },
        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{name}: </td>' +
                '<td style="padding:0"><b>{point.y:1f} </b></td></tr>',
            footerFormat: '</table>',
            shared: true

        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: false
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'Scheme Category',
            colorByPoint: true,
            data: [{
                name: 'Agriculture',
                y: 61,
                //sliced: true,
               // selected: true
            }, {
                name: 'Livestock',
                y: 11
            }, {
                name: 'Fisheries',
                y: 10
            }, {
                name: 'Off-Farm',
                y: 4
            }]
        }]
    });

</script>


<script>


    // Build the chart
    Highcharts.chart('AmountDisbursed', {
        chart: {
            plotBackgroundColor: null,
            plotBorderWidth: null,
            plotShadow: false,
            type: 'pie'
        },
        title: {
            text: 'Amount Disbursed'
        },
        //tooltip: {
        //    pointFormat: '{series.name}: <b>{point.percentage:.1f}%</b>'
        //},

        tooltip: {
            headerFormat: '<span style="font-size:10px">{point.key}</span><table>',
            pointFormat: '<tr><td style="color:{series.color};padding:0">{name}: </td>' +
                '<td style="padding:0"><b>{point.y:1f} BDT</b></td></tr>',
            footerFormat: '</table>',
            shared: true

        },
        plotOptions: {
            pie: {
                allowPointSelect: true,
                cursor: 'pointer',
                dataLabels: {
                    enabled: false
                },
                showInLegend: true
            }
        },
        series: [{
            name: 'Scheme Category',
            colorByPoint: true,
            data: [{
                name: 'Agriculture',
                y: 10000,
                //sliced: true,
                //selected: true
            }, {
                name: 'Livestock',
                y: 30000
            }, {
                name: 'Fisheries',
                y: 10000
            }, {
                name: 'Off-Farm',
                y: 50000
            }]
        }]
    });

</script>

Finix.UI/Areas/ATM/Views/Scheme/SchemeCategory.cshtml
@{
    ViewBag.Title = "SchemeCategory";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/Scheme/SchemeCategory.js"></script>

<div class="panel-body rm" id="divScheme">
    <br />
    <div class="container-fluid">
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Category Name<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-6" data-bind="validationElement:CategoryName">
                <input type="text" class="form-control" data-bind="value:CategoryName,valueUpdate: 'keyup'" placeholder="Type a Name" value="">
            </div>

        </div>

        <br />
        <div class="form-group row row_design">

            <div class="col-sm-2 col-sm-offset-9">
                <button type="submit" class="btn btn-success" data-bind="enable: IsValid" data-toggle="modal" data-target="#myModal">Submit</button>
            </div>
        </div>
    </div>

    <hr />
    <div class="panel">
        <div class="panel-heading">
            <header>List of Scheme Category</header>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="headcolor">
                        <tr>
                            <th>Category Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach:Categories">
                        <tr>
                            <td class="center" data-bind="text:CategoryName"></td>
                            <td class="center">
                                <button type="button" data-bind='click: $parent.editCategory' title="Edit">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </button>

                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    <div class="form-group">
        <div id="successModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Response</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p id="successModalText"></p>
                        <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Confirmation</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p>Do you want to add this Category?</p>
                        <button data-bind="click: SaveCategory" class="btn btn-success" data-dismiss="modal">Yes</button>
                        <button type="button" class="btn btn-success" data-dismiss="modal">No</button>

                    </div>
                    <div class="modal-footer">
                        
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>

Finix.UI/Areas/ATM/Views/Scheme/SchemeList.cshtml
@using PagedList.Mvc;
@model PagedList.IPagedList<Finix.ATM.DTO.SchemeInformationDto>
@{
    ViewBag.Title = "SchemeList";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
    var jss = new System.Web.Script.Serialization.JavaScriptSerializer();
    var pageDataJson = jss.Serialize(Model);
    var ThanasJson = jss.Serialize(ViewBag.Thanas);
    var UPsJson = jss.Serialize(ViewBag.UPs);
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<link href="~/Content/PagedList.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/Scheme/SchemeList.js"></script>

<script>
    var pageData = JSON.parse('@Html.Raw(pageDataJson)');
    var ups = JSON.parse('@Html.Raw(UPsJson)');
    var thanas = JSON.parse('@Html.Raw(ThanasJson)');
    var thana = '@ViewBag.Thana'
    var up = '@ViewBag.UP'
    var searchString = '@ViewBag.SearchString'
</script>




<div class="panel-body rm" id="divSchemeListVM">
    <br />

    <div class="panel-body">
        <div class="container-fluid">
            @using (Ajax.BeginForm("SchemeList", "Scheme", null))
    {
                <div class="form-group row row_design">
                    <div class="col-sm-offset-1 col-sm-2">
                        <label class="control-label">Search by Scheme Name<span class="required">*</span> :</label>
                    </div>
                    <div class="col-sm-3" >
                        <input type="text" name="searchString" class="form-control" data-bind="value:SchemeTitle,valueUpdate: 'keyup'" id="searchString" placeholder="Scheme Name" value="@(ViewBag.SearchString ?? String.Empty)" />
                    </div>

                </div>

                <div class="form-group row row_design">
                    <div class="col-sm-offset-1 col-sm-2">
                        <label class="control-label">Search by Thana<span class="required">*</span> :</label>
                    </div>
                    <div class="col-sm-3" >
                        <select type="text" class="form-control" name="locationid" data-bind="options:Thanas, value: Thana, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>
                    </div>
                    <div class="col-sm-2">
                        <label class="control-label">Search by UP<span class="required">*</span> :</label>
                    </div>
                    <div class="col-sm-3" >
                        <select type="text" class="form-control" name="up" data-bind="options:UPs, value: UP, optionsCaption:'Choose One..', optionsValue:'Id', optionsText: 'LocationName'"></select>
                    </div>
                </div>



                <br />
                <div class="form-group row row_design">

                    <div class="col-sm-2 col-sm-offset-10">
                        <button type="submit" class="btn btn-deepgreen" >Search</button>
                    </div>
                </div>
            }
        </div>


        <hr />
        <div class="panel">

            <div class="panel-body">
                <div class="table-responsive">
                    <table class="table table-striped table-bordered">
                        <thead class="headcolor">
                            <tr>

                                <th>Scheme Title</th>
                                <th>Location Name</th>
                                <th>Scheme No</th>
                                <th>Budget</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody data-bind="foreach:PageData">
                            <tr>

                                <td class="center" data-bind="text:SchemeTitle"></td>
                                <td class="center" data-bind="text:LocationName"></td>
                                <td class="center" data-bind="text:SchemeNo"></td>
                                <td class="center" data-bind="text:EstimatedBudget"></td>
                                <td class="center">
                                    <button type="button"  class="btn btn-default" data-bind='click: $parent.Edit'>
                                        <span class="glyphicon glyphicon-edit"></span>
                                    </button>
                                </td>

                            </tr>
                        </tbody>
                    </table>
                </div>

                <div class="pagination-centered">
                    Page @(Model.PageCount < Model.PageNumber ? 0 : Model.PageNumber) of @Model.PageCount
                    @Html.PagedListPager(Model, page => Url.Action("SchemeList",
                                                        new
                                                        {
                                                            page,
                                                            sortOrder = ViewBag.CurrentSort,
                                                            searchString = ViewBag.SearchString,
                                                            thana = ViewBag.Thana,
                                                            up = ViewBag.UP,
                                                            currentFilter = ViewBag.CurrentFilter
                                                        }))


                </div>
            </div>
        </div>

        
    </div>
</div>

Finix.UI/Areas/ATM/Views/Scheme/SchemeNature.cshtml
@{
    ViewBag.Title = "SchemeNature";
    Layout = "~/Views/Shared/_LayoutjqGrid.cshtml";
}

<link href="~/Content/customassets/css/Cart.css" rel="stylesheet" />
<script src="~/Areas/ATM/Scripts/Scheme/SchemeNature.js"></script>

<div class="panel-body rm" id="divScheme">
    <br />
    <div class="container-fluid">
        <div class="form-group row row_design">
            <div class="col-sm-offset-2 col-sm-2">
                <label class="control-label">Nature Name<span class="required">*</span> :</label>
            </div>
            <div class="col-sm-6" data-bind="validationElement:NatureName">
                <input type="text" class="form-control" data-bind="value:NatureName,valueUpdate: 'keyup'" placeholder="Type a Name" value="">
            </div>

        </div>

        <br />
        <div class="form-group row row_design">

            <div class="col-sm-2 col-sm-offset-9">
                <button type="submit" class="btn btn-success" data-bind="enable: IsValid" data-toggle="modal" data-target="#myModal">Submit</button>
            </div>
        </div>
    </div>

    <hr />
    <div class="panel">
        <div class="panel-heading">
            <header>List of Scheme Natures</header>
        </div>
        <div class="panel-body">
            <div class="table-responsive">
                <table class="table table-striped table-bordered">
                    <thead class="headcolor">
                        <tr>
                            <th>Nature Name</th>
                            <th>Action</th>
                        </tr>
                    </thead>
                    <tbody data-bind="foreach:Natures">
                        <tr>
                            <td class="center" data-bind="text:NatureName"></td>
                            <td class="center">
                                <button type="button" data-bind='click: $parent.editNature' title="Edit">
                                    <span class="glyphicon glyphicon-edit"></span>
                                </button>

                            </td>
                        </tr>
                    </tbody>
                </table>

            </div>
        </div>
    </div>
    <div class="form-group">
        <div id="successModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">
                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Response</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p id="successModalText"></p>
                        <button type="button" class="btn btn-success" data-dismiss="modal">Ok</button>
                    </div>
                    <div class="modal-footer">
                    </div>
                </div>
            </div>
        </div>
        <div id="myModal" class="modal fade" role="dialog">
            <div class="modal-dialog modal-sm">

                <!-- Modal content-->
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal">&times;</button>
                        <h4 class="modal-title">Confirmation</h4>
                    </div>
                    <div class="modal-body" align="center">
                        <p>Do you want to add this Nature?</p>
                        <button data-bind="click: SaveNature" class="btn btn-success" data-dismiss="modal">Yes</button>
                        <button type="button" class="btn btn-success" data-dismiss="modal">No</button>

                    </div>
                    <div class="modal-footer">

                    </div>
                </div>

            </div>
        </div>
    </div>
</div>